[package]
name = "rust_typescript_tools"
version = "0.0.0-semantically-released"
edition = "2021"

[[bin]]
name = "monorepo"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.5"
globwalk = "0.8.1"
pathdiff = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }

[dev-dependencies]
semantic-release-rust = "1.0.0-alpha.8"
