---
name: Check Dependencies

on: [pull_request]

jobs:
  check_licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: 1.60.0
          command: check licenses

  check_sources:
    name: Check sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: 1.60.0
          command: check sources
