---

name: Check Sources

on: [ pull_request ]

jobs:
  check_sources:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check sources
