---
name: CI

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: monorepo
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install GNU/Linux toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
