---
name: Release

on:
  push:
    branches: [master, alpha, beta]

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

# semantic-release is built around the following idea:
#
# > A release consist in running test, defining the version then releasing
#
# - https://github.com/semantic-release/semantic-release/issues/753#issuecomment-384689034
#
# So we perform the following actions from the context of semantic-release plugins:
#
# - compile all target binaries
# - docker build and publish
# - npm publish
# - create GitHub release

env:
  BINARY_NAME: monorepo
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  get-next-version:
    name: Calculate next release
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all history and tags for calculating next semantic version
          fetch-depth: 0

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Calculate next semantic-release version
        id: calculate
        run: echo "next-version=$(npx standard-version --dry-run | grep "tagging release" | awk '{ print $NF }')" >> $GITHUB_OUTPUT

  # Room for improvement regarding caching/work-skipping. One example here
  # https://github.com/ClementTsang/bottom/blob/92ec3599363c710815c286e975bbb6cc748708dd/.github/workflows/ci.yml#L195

  ### Compile release artifacts
  build-release:
    name: Build CLI ${{ matrix.triple.target }}
    runs-on: ${{ matrix.triple.os }}
    container: ${{ matrix.triple.container }}
    needs:
      - get-next-version

    strategy:
      matrix:
        triple:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-musl", cross: false }
          - { os: "ubuntu-latest", target: "i686-unknown-linux-musl", cross: true }
          - { os: "macOS-latest", target: "x86_64-apple-darwin", cross: false }
          # aarch64
          - { os: "ubuntu-latest", target: "aarch64-unknown-linux-musl", cross: true }
          # macOS ARM
          - { os: "macOS-latest", target: "aarch64-apple-darwin", cross: true }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: stable
          target: ${{ matrix.triple.target }}

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Cache cargo
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install semantic-release-cargo
        if: needs.get-next-version.outputs.new-release-published == 'true'
        uses: taiki-e/install-action@v1
        with:
          tool: semantic-release-cargo@2

      - name: Prepare semantic-release for Rust
        if: needs.get-next-version.outputs.new-release-published == 'true'
        run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}

      - name: Cross-compile release binary
        if: matrix.triple.cross == true
        run: cross build --bin monorepo --release --target ${{ matrix.triple.target }} --verbose

      - name: Compile release binary
        if: matrix.triple.cross == false
        run: cargo build --bin monorepo --release --target ${{ matrix.triple.target }} --verbose

      - name: Create release archive
        run: |
          mkdir dist
          mkdir -p builds/typescript-tools-${{ matrix.triple.target }}
          cp target/${{ matrix.triple.target }}/release/monorepo builds/typescript-tools-${{ matrix.triple.target }}/
          tar -C builds -czvf dist/typescript-tools-${{ matrix.triple.target }}.tar.gz typescript-tools-${{ matrix.triple.target }}

      # Create a checksum of the tar archive for manual checksum verification of the archive before extraction.
      - name: Create tar checksum
        run: shasum --algorithm 256 typescript-tools-${{ matrix.triple.target }}.tar.gz > typescript-tools-${{ matrix.triple.target }}-SHASUMS256.txt
        working-directory: ./dist

      # Create a checksum of the binary for automatic checksum verification in the post-install hook. In this code
      # path, the tar archive is streamed from the GitHub release page and the stream is untarred before a file
      # is ever written to disk, to minimize disk usage. This makes it impossible to validate the checksum of the
      # entire tar archive, so we calculate a checksum of the untarred binary instead.
      - name: Create binary checksum
        run: shasum --algorithm 256 --binary monorepo | tee ../../dist/typescript-tools-${{ matrix.triple.target }}-binary-SHASUMS256.txt
        working-directory: ./builds/typescript-tools-${{ matrix.triple.target }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.triple.target }}
          path: |
            dist/typescript-tools-${{ matrix.triple.target }}.tar.gz
            dist/typescript-tools-${{ matrix.triple.target }}-binary-SHASUMS256.txt
            dist/typescript-tools-${{ matrix.triple.target }}-SHASUMS256.txt
          if-no-files-found: error
          retention-days: 1

  ### Perform the semantic-release
  release:
    runs-on: ubuntu-latest
    needs:
      - build-release

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: stable

      - name: Cache cargo
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Display downloaded release artifacts
        run: ls -R
        working-directory: dist

      - name: Combine checksums
        run: cat dist/**/typescript-tools-*-SHASUMS256.txt | tee npm/SHASUMS256.txt

      - name: Invoke semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
